version: "3"
networks:
  app-tier:
    driver: bridge
services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    depends_on:
      - mariadb
    networks:
      - app-tier
    ports:
      - 9002:9000
    volumes:
      - .:/srv/app
    links:
      - mariadb:mariadb
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    networks:
      - app-tier
    ports:
      - 8080:80
    volumes:
      - ./public:/srv/app/public
  mariadb:
    networks:
      - app-tier
    image: mariadb:10.3
    ports:
      - "13306:3306"
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=secret
