version: "3"
networks:
  app-tier:
    driver: bridge
volumes:
  mysqldata:
    driver: "local"
  redisdata:
    driver: "local"
services:
  app:
    container_name: laravel-app
    env_file: .docker.env
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    networks:
      - app-tier
    ports:
      - 9002:9000
    volumes:
      - .:/srv/app
  nginx:
    container_name: laravel-nginx
    depends_on:
      - mariadb
      - redis
      - app
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    networks:
      - app-tier
    volumes:
      - ./public:/srv/app/public
  mariadb:
    container_name: laravel-database
    env_file: .docker.env
    image: mariadb:10.3
    restart: always
    container_name: mariadb
    ports:
      - "13306:3306"
    networks:
      - app-tier
    volumes:
     - mysqldata:/var/lib/mysql
  redis:
    image: redis:alpine
    volumes:
     - redisdata:/data
    networks:
     - app-tier
  varnish:
    container_name: laravel-varnish
    tty: true
    depends_on:
      - nginx
    restart: always
    build:
      context: .
      dockerfile: .docker/varnish/Dockerfile
    networks:
      - app-tier
    ports:
      - 8080:8080
    command: 'sh start'
    volumes:
      - .docker/varnish/default.vcl:/etc/varnish/default.vcl
  # supervisor:
  #   container_name: laravel-supervisor
  #   build:
  #     context: .
  #     dockerfile: .docker/supervisor/Dockerfile
  #   depends_on:
  #     - nginx
  #     - app
  #   restart: always
  #   volumes:
  #     - .docker/supervisor/supervisor.conf:/etc/supervisor/conf.d