version: "3"
networks:
  app-tier:
    driver: bridge
volumes:
  mysqldata:
    driver: "local"
  redisdata:
    driver: "local"
services:
  app:
    env_file: .docker.env
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    networks:
      - app-tier
    ports:
      - 9002:9000
    volumes:
      - .:/srv/app
  nginx:
    depends_on:
      - mariadb
      - redis
      - app
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    networks:
      - app-tier
    volumes:
      - ./public:/srv/app/public
  mariadb:
    env_file: .docker.env
    image: mariadb:10.3
    restart: always
    container_name: mariadb
    ports:
      - "13306:3306"
    networks:
      - app-tier
    volumes:
     - mysqldata:/var/lib/mysql
  redis:
    image: redis:alpine
    volumes:
     - redisdata:/data
    networks:
     - app-tier
  varnish:
    tty: true
    depends_on:
      - nginx
    restart: always
    build:
      context: .
      dockerfile: .docker/varnish/Dockerfile
    networks:
      - app-tier
    ports:
      - 8080:8080
    command: 'sh start'
    volumes:
      - .docker/varnish/default.vcl:/etc/varnish/default.vcl
